export enum ColumnDescription {
    patent = 'Patente',
    name = 'Nombre',
    surname = 'Apellido',
    legajo = 'Legajo',
    type = 'Tipo',
    description = 'Descripcion',
    batea = 'Patente <br> Batea',
    trailer = 'Patente <br> Acoplado',
    email = 'Email',
    rol = 'Rol',
    localIni = 'Localidad <br> Inicio',
    localFin = 'Localidad <br> Fin',
    fechaIni = 'Fecha <br> Inicio',
    fechaFin = 'Fecha <br> Fin',
    reparacion = 'Descripcion <br> Reparación', 
    costo = 'Costo <br> Reparación',
    fechaReparacion = 'Fecha <br> Reparación',
    descEquipo = 'Equipo'
} 