export enum ColumnDescription {
    patent = 'Patente',
    name = 'Nombre',
    surname = 'Apellido',
    legajo = 'Legajo',
    type = 'Tipo',
    description = 'Descripcion',
    batea = 'Patente Batea',
    trailer = 'Patente Acoplado',
    email = 'Email',
    rol = 'Rol',
    localIni = 'Localidad Inicio',
    localFin = 'Localidad Fin',
    fechaIni = 'Fecha Inicio',
    fechaFin = 'Fecha Fin',
} 